pythonApi:
  replicaCount: 2

  image:
    repository: python-api
    tag: latest
    pullPolicy: Never

  service:
    type: ClusterIP
    port: 80
    targetPort: 8000


redis:
  replicaCount: 1

  image:
    repository: redis
    tag: "7"

  host: redis
  port: 6379

  password: redis-123

  service:
    type: ClusterIP
    port: 6379
    targetPort: 6379

  persistence:
    enabled: true
    size: 1Gi
    storageClassName: standard


ingress:
  enabled: true

  className: nginx

  host: localhost

  path: /api(/|$)(.*)

  pathType: ImplementationSpecific