apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: redis-assignment
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/dbenavi5/redis-assignment.git
    targetRevision: main
    path: helm/redis-assignment

    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
