{{- if and .Values.istio.enabled .Values.istio.gateway.enabled }}

apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: fastapi-istio-route

spec:
  hosts:
    - {{ .Values.istio.gateway.host | quote }}

  gateways:
    - fastapi-istio-gateway

  http:
    - match:
        - uri:
            regex: "^/api(/|$)(.*)"

      rewrite:
        uriRegexRewrite:
          match: "^/api(/|$)(.*)"
          rewrite: "/\\2"

      route:
        - destination:
            host: python-api.default.svc.cluster.local

            port:
              number: {{ .Values.pythonApi.service.port }}

{{- end }}