{{- if and .Values.istio.enabled .Values.istio.mtls.redisStrict }}

apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: redis-strict-mtls

spec:
  selector:
    matchLabels:
      app: redis

  mtls:
    mode: STRICT

{{- end }}