apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis

spec:
  replicas: {{ .Values.redis.replicaCount }}

  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis

        {{- if and .Values.istio.enabled .Values.istio.sidecarInjection }}
        sidecar.istio.io/inject: "true"
        {{- end }}

    spec:
      containers:
        - name: redis

          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"

          ports:
            - name: tcp-redis
              containerPort: {{ .Values.redis.port }}

          command:
            - redis-server

          args:
            - --appendonly
            - "yes"

          {{- if .Values.redis.persistence.enabled }}
          volumeMounts:
            - name: redis-storage
              mountPath: /data
          {{- end }}

      {{- if .Values.redis.persistence.enabled }}
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
      {{- end }}